
lines = []
lines.append("# Tasks: json-http-ingestion\n")
lines.append("\n")
lines.append("## Task Dependency Graph\n")
lines.append("\n")
lines.append("```\n")
lines.append("Task 1  (Project Scaffolding)\n")
lines.append("  └─► Task 2  (Configuration & AppConfig)\n")
lines.append("        └─► Task 3  (DynamoDB Table & ReadingItem)\n")
lines.append("              └─► Task 4  (Core Domain Models)\n")
lines.append("                    ├─► Task 5  (PayloadParser)          ─┐\n")
lines.append("                    ├─► Task 6  (ReadingValidator)        │\n")
lines.append("                    ├─► Task 7  (DuplicateFilter)         ├─► Task 9  (IngestController)\n")
lines.append("                    └─► Task 8  (StorageService)          │\n")
lines.append("                    └─► Task 10 (QueryHandler)           ─┘\n")
lines.append("                          └─► Task 11 (ReadingsController)\n")
lines.append("                                └─► Task 12 (HealthController)\n")
lines.append("                                      └─► Task 13 (React Frontend)\n")
lines.append("                                            └─► Task 14 (Integration Tests)\n")
lines.append("                                                  └─► Task 15 (Dockerfile & CI/CD)\n")
lines.append("```\n")
lines.append("\n")
lines.append("> **Reading the graph**: an arrow means the pointed-to task depends on the pointing task.\n")
lines.append("> Tasks 5–10 can be developed in parallel once Task 4 is complete.\n")
lines.append("> Task 9 (IngestController) requires Tasks 5, 6, 7, and 8 to be complete.\n")
lines.append("> Task 11 (ReadingsController) requires Task 10 to be complete.\n")
lines.append("\n")
lines.append("---\n")
lines.append("\n")
lines.append("## Tasks\n")
lines.append("\n")

with open(r'c:\Users\walke\git\tempmon2\.kiro\specs\json-http-ingestion\tasks.md', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Header written:", len(lines), "lines")
